export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const JOBS_FETCH_START = "JOBS_FETCH_START";
export const JOBS_FETCH_SUCCESS = "JOBS_FETCH_SUCCESS";
export const JOBS_FETCH_FAIL = "JOBS_FETCH_FAIL";

export const FILTERS_FETCH_START = "FILTERS_FETCH_START";
export const FILTERS_FETCH_SUCCESS = "FILTERS_FETCH_SUCCESS";
export const FILTERS_FETCH_FAIL = "FILTERS_FETCH_FAIL";
